/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col w-full max-md:max-w-full">
      <div className="flex gap-4 justify-center items-center min-h-[165px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf5c8be328d20ea9adf40a8e712630a226cc3b7a1ecace0aa9dab3f326d33261?placeholderIfAbsent=true&apiKey=4d41f6c15a964c1bb94820575475574a"
          alt="Footer logo"
          className="object-contain self-stretch my-auto aspect-[4.69] w-[150px]"
        />
      </div>
    </footer>
  );
};

export default Footer;
