name: Deploy Portfolio Website

on:
  # trigger on:
  #  - creation
  #  - direct code push to the main branch
  #  - manual trigger
  release:
    types: [created]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  publish:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm ci

      # - name: Deploy
      #   uses: Dylan700/sftp-upload-action@latest
      #   with:
      #     server: ${{secrets.IONOS_SERVER}}
      #     username: ${{secrets.IONOS_USER}}
      #     password: ${{secrets.IONOS_PASSWORD}}
      #     port: 22
      #     uploads: |
      #         ./build/ => ./kunden/homepages/28/d1018479829/htdocs/

      - name: Build
        run: npm run build

      # - name: Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{secrets.IONOS_SERVER}}
      #     username: ${{secrets.IONOS_USER}}
      #     password: ${{secrets.IONOS_PASSWORD}}
      #     local-dir: ./build/

      - name: Deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          # remote-host: ${{secrets.IONOS_SERVER}}
          remote-host: access1018479829.webspace-data.io
          # remote-user: ${{secrets.IONOS_PASSWORD}}
          remote-user: acc309474922
          # remote-password: ${{ secrets.IONOS_PASSWORD }}
          remote-password: 238f466b-bb5f-437f-b5fd-0fe8c3891a0f
          remote-path: /portfolio/001-2024
          local-path: ./build/
          debug: true
