name: Deploy Portfolio Website

on:
  # trigger on:
  #  - creation
  #  - direct code push to the main branch
  #  - manual trigger
  release:
    types: [created]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy with
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{secrets.IONOS_TEST_SERVER}}
          remote-user: ${{ secrets.IONOS_TEST_USER }}
          remote-password: ${{secrets.IONOS_TEST_PASSWORD}}
          remote-path: /portfolio/001-2024
          local-path: ./build/
          debug: true